// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniMonitor.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniMonitor.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720172037_AddCapturedAtIndex")]
    partial class AddCapturedAtIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniMonitor.Api.Data.ActivitySample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.Property<string>("WindowTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("window_title");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("ix_activity_samples_captured_at_utc");

                    b.ToTable("activity_samples", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
